title: Chirag Mahajan # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer, Backend
  <br><br>
  <a href="mailto:mahajan1997@gmail.com">mahajan1997@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/chirag-mahajan-bb59b73b">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/chiragmahajan">Gihub</a> 
theme: jekyll-theme-minimal
